# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_2/design_1_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_7/design_1_axi_dma_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_7 || ORIG_REF_NAME==design_1_axi_dma_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_8/design_1_ps8_0_axi_periph_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_8 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_100M_7/design_1_rst_ps8_0_100M_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_100M_7 || ORIG_REF_NAME==design_1_rst_ps8_0_100M_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_8/design_1_axi_smc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_8 || ORIG_REF_NAME==design_1_axi_smc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mlp_sigmoid_0_0/design_1_mlp_sigmoid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mlp_sigmoid_0_0 || ORIG_REF_NAME==design_1_mlp_sigmoid_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# XDC: /home/steve/Desktop/capstone/test_vivado/test_9_streammul/test_9_streammul.gen/sources_1/bd/design_1/design_1_ooc.xdc
