# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/steve/Desktop/capstone/test_vivado/test_9_streammul/test_9_streammul.srcs/sources_1/bd/design_1/ip/design_1_mlp_sigmoid_0_0/design_1_mlp_sigmoid_0_0.xci
# IP: The module: 'design_1_mlp_sigmoid_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/steve/Desktop/capstone/test_vivado/test_9_streammul/test_9_streammul.gen/sources_1/bd/design_1/ip/design_1_mlp_sigmoid_0_0/constraints/mlp_sigmoid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mlp_sigmoid_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/steve/Desktop/capstone/test_vivado/test_9_streammul/test_9_streammul.srcs/sources_1/bd/design_1/ip/design_1_mlp_sigmoid_0_0/design_1_mlp_sigmoid_0_0.xci
# IP: The module: 'design_1_mlp_sigmoid_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/steve/Desktop/capstone/test_vivado/test_9_streammul/test_9_streammul.gen/sources_1/bd/design_1/ip/design_1_mlp_sigmoid_0_0/constraints/mlp_sigmoid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mlp_sigmoid_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
